name: 'Display message'
description: 'Runs a python script that sets up a message as github output.'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: display message
      run: python -m print_message
      shell: bash

