name: Continue on error

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  failing_job:
    runs-on: ubuntu-latest

    steps:
      - name: Fail on purpose
        run: |
          echo "This job is failing..."
          exit 1

  run_on_failure_job:
    runs-on: ubuntu-latest
    needs: [failing_job]
    if: failure()
    steps:
        - name: Acknowledge run
          run: |
            echo "This is job is running due to a previous job failure..."
        
        - name: Ensure overall workflow fails
          run: |
            echo "Now that the error action occured, the whole workflow will fail..."
            exit 1
        
