name: Validate PR Branches

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current GitHub Actions workflow repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Hello
        id: hello
        run: |
            python print_message.py
      - name: Display Hello
        run: |
            echo "${{ steps.hello.outputs.message }}"