name: Validate PR Branches

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source and target branches
        env:
          PR_TARGET: ${{ github.event.pull_request.base.ref }}
          PR_SOURCE: ${{ github.event.pull_request.head.ref }}
        run: |
          echo "Target Branch: $PR_TARGET"
          echo "Source Branch: $PR_SOURCE"

          # Define allowed branches
          if [ "$PR_TARGET" = "main" ]; then
            if [ "$PR_SOURCE" != "uat" ]; then
              echo "You can only create a PR to 'main' from 'uat'!"
              exit 1
            fi
          elif [ "$PR_TARGET" = "uat" ]; then
            if [ "$PR_SOURCE" != "dev" ]; then
              echo "You can only create a PR to 'uat' from 'dev'!"
              exit 1
            fi
          else
            echo "PR validation passed."
          fi
